CREATE ROLE roliq_app LOGIN PASSWORD 'roliq_app' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE roliq_worker LOGIN PASSWORD 'roliq_worker' NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
GRANT CONNECT ON DATABASE roliq TO roliq_app, roliq_worker;
GRANT USAGE ON SCHEMA public TO roliq_app, roliq_worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO roliq_app, roliq_worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO roliq_app, roliq_worker;
