/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check process liveness */
    get: operations["liveness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check dependency readiness */
    get: operations["readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/session/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bootstrap the current application session
     * @description Idempotently provisions an application user and personal organization from verified OIDC claims.
     */
    post: operations["bootstrapSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the active user and workspace */
    get: operations["getSessionContext"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the persisted dashboard summary */
    get: operations["getDashboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/onboarding": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get onboarding progress */
    get: operations["getOnboarding"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update onboarding progress */
    patch: operations["updateOnboarding"];
    trace?: never;
  };
  "/v1/career-profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the structured career profile */
    get: operations["getCareerProfile"];
    /** Replace the structured career profile */
    put: operations["replaceCareerProfile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/resumes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List resumes for the current user */
    get: operations["listResumes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/resume-uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a secure resume upload intent */
    post: operations["createResumeUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/resume-uploads/{uploadId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify and complete a resume upload */
    post: operations["completeResumeUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    OnboardingStatus: "not_started" | "in_progress" | "completed";
    Onboarding: {
      currentStep: number;
      status: components["schemas"]["OnboardingStatus"];
      /** @enum {string} */
      profileMethod?: "resume" | "manual";
      /** Format: date-time */
      completedAt?: string;
    };
    SessionContext: {
      user: {
        /** Format: uuid */
        id: string;
        /** Format: email */
        email: string;
        displayName: string;
      };
      organization: {
        /** Format: uuid */
        id: string;
        name: string;
        slug: string;
        /** @enum {string} */
        type: "personal" | "team";
      };
      onboarding: components["schemas"]["Onboarding"];
    };
    CareerProfile: {
      headline: string;
      summary: string;
      countryCode: string;
      timeZone: string;
      city: string;
      yearsExperience?: number;
      skills: string[];
      experiences: components["schemas"]["Experience"][];
      education: components["schemas"]["Education"][];
      /** Format: date-time */
      readonly updatedAt?: string;
    };
    Experience: {
      /** Format: uuid */
      id?: string;
      company: string;
      title: string;
      location?: string;
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate?: string;
      isCurrent: boolean;
      description?: string;
    };
    Education: {
      /** Format: uuid */
      id?: string;
      institution: string;
      degree?: string;
      fieldOfStudy?: string;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
    };
    Resume: {
      /** Format: uuid */
      id: string;
      fileName: string;
      /** @enum {string} */
      status:
        | "pending"
        | "uploaded"
        | "scanning"
        | "ready"
        | "rejected"
        | "failed";
      rejectionReason?: string;
      /** Format: date-time */
      createdAt: string;
    };
    UploadIntent: {
      /** Format: uuid */
      uploadId: string;
      /** Format: uuid */
      resumeId: string;
      /** Format: uri */
      uploadUrl: string;
      objectKey: string;
      /** Format: date-time */
      expiresAt: string;
      requiredHeaders: {
        [key: string]: string;
      };
    };
    Dashboard: {
      profileCompletion: number;
      onboarding: components["schemas"]["Onboarding"];
      profile?: components["schemas"]["CareerProfile"] | null;
      resumes: components["schemas"]["Resume"][];
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      code: string;
      detail: string;
      requestId: string;
      fields?: {
        [key: string]: string;
      };
    };
  };
  responses: {
    /** @description RFC 9457-compatible error */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    /** @description Active organization. The personal workspace is selected when omitted. */
    OrganizationId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Required dependencies are available */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      503: components["responses"]["Problem"];
    };
  };
  bootstrapSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current tenant context */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionContext"];
        };
      };
      401: components["responses"]["Problem"];
    };
  };
  getSessionContext: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current tenant context */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionContext"];
        };
      };
      403: components["responses"]["Problem"];
    };
  };
  getDashboard: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Persisted dashboard summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Dashboard"];
        };
      };
    };
  };
  getOnboarding: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current onboarding progress */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Onboarding"];
        };
      };
    };
  };
  updateOnboarding: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          currentStep?: number;
          status?: components["schemas"]["OnboardingStatus"];
          /** @enum {string} */
          profileMethod?: "resume" | "manual";
        };
      };
    };
    responses: {
      /** @description Updated progress */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Onboarding"];
        };
      };
      422: components["responses"]["Problem"];
    };
  };
  getCareerProfile: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Career profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CareerProfile"];
        };
      };
    };
  };
  replaceCareerProfile: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CareerProfile"];
      };
    };
    responses: {
      /** @description Saved career profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CareerProfile"];
        };
      };
      422: components["responses"]["Problem"];
    };
  };
  listResumes: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Resumes owned by the current user in the active organization */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Resume"][];
          };
        };
      };
    };
  };
  createResumeUpload: {
    parameters: {
      query?: never;
      header: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          fileName: string;
          /** @enum {string} */
          contentType:
            | "application/pdf"
            | "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
          sizeBytes: number;
          checksumSha256: string;
        };
      };
    };
    responses: {
      /** @description Short-lived presigned upload intent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadIntent"];
        };
      };
      422: components["responses"]["Problem"];
    };
  };
  completeResumeUpload: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization. The personal workspace is selected when omitted. */
        "X-Organization-ID"?: components["parameters"]["OrganizationId"];
      };
      path: {
        uploadId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Verified upload queued for security scanning */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Resume"];
        };
      };
      404: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
}
